CREATE DATABASE IF NOT EXISTS ezp_18x DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS ezp_17x DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS ezp_16x DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS ezp_54x DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE USER 'ezp'@'%' IDENTIFIED BY 'publish';

GRANT ALL PRIVILEGES ON ezp_18x.* TO 'ezp'@'%';
GRANT ALL PRIVILEGES ON ezp_17x.* TO 'ezp'@'%';
GRANT ALL PRIVILEGES ON ezp_16x.* TO 'ezp'@'%';
GRANT ALL PRIVILEGES ON ezp_54x.* TO 'ezp'@'%';

FLUSH PRIVILEGES;
