#!/usr/bin/env bash

alias bc='env bc --mathlib'
alias cat='env cat --squeeze-blank'
alias chromium-browser='env chromium-browser --process-per-site'
alias chromium='env chromium-browser --process-per-site'
alias cp='env cp --verbose --interactive --recursive'
alias df='env df --block-size=1K --human-readable'
alias du='env du --total --human-readable --summarize'
alias echo='env echo -e'
alias egrep='env egrep --ignore-case --color=always'
alias eyeD3='env eyeD3 --force-update --verbose'
alias free='env free --mega --human --total'
alias google-chrome='env google-chrome --process-per-site'
alias grep='env grep --ignore-case --color=always'
alias latexmk='env latexmk -f -g -halt-on-error -aux-directory=/tmp -output-directory=/tmp'
alias ls='env ls --color --quote-name --file-type --si'
alias mkdir='env mkdir --parents'
alias mv='env mv --verbose --interactive'
alias mysqldump='env mysqldump --host=${SQL_HOST} --user=${SQL_USER} --password=${SQL_PASSWORD}'
alias mysql='env mysql --host=${SQL_HOST}  --user=${SQL_USER} --password=${SQL_PASSWORD}'
alias ps='env ps -H -e --sort=ruser --lines 30 -o"%p   %P   %U %t     %c" --headers --forest '
alias ripit='env ripit --outputdir ~/CDRip --coder 0 --bitrate 320 --tracktemplate '"'"'"$tracknum - $trackname"'"'"' --dirtemplate '"'"'"$artist/$album"'"'"
alias sl='env games/sl -ale'
alias sort='env sort --ignore-leading-blanks --ignore-case --unique --ignore-nonprinting'
alias syndaemon='env syndaemon -d -K -i 2'
alias toilet='env toilet --metal --width 1100 --font=future'
alias tree='env tree -d --noreport'
alias gitTime="env git commit -m \"$(date +'%Y-%m-%d %H:%M')\""

