#!/bin/bash
# Show a nicely formatted list fo all branches
# Push the commit to the remote repository.

git for-each-ref \
    --sort=-committerdate refs/heads/ \
    --sort=-committerdate \
    --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
