#!/bin/bash
# Show a nicely formatted list with the lastest changes

git whatchanged \
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' \
    --abbrev-commit \
    --date=relative \
    --name-status
