#!/usr/bin/env bash
# vi:syntax=bash
# http://misc.flogisoft.com/bash/tip_colors_and_formatting

# ●▬▬▬▬▬๑۩  Foreground ۩๑▬▬▬▬▬●
export FORE_RESET='\e[0;49m'
export FORE_BLACK='\e[0;30m'
export FORE_WHITE='\e[1;37m'
export FORE_BLUE_DARK='\e[0;34m'
export FORE_BLUE_LIGHT='\e[1;34m'
export FORE_CYAN_DARK='\e[0;36m'
export FORE_CYAN_LIGHT='\e[1;36m'
export FORE_GRAY_DARK='\e[0;90m'
export FORE_GRAY_LIGHT='\e[037m'
export FORE_GREEN_DARK='\e[0;32m'
export FORE_GREEN_LIGHT='\e[1;32m'
export FORE_MAGENTA_DARK='\e[0;35m'
export FORE_MAGENTA_LIGHT='\e[1;35m'
export FORE_RED_DARK='\e[0;31m'
export FORE_RED_LIGHT='\e[1;31m'
export FORE_YELLOW_DARK='\e[0;33m'
export FORE_YELLOW_LIGHT='\e[1;33m'

# ●▬▬▬▬▬๑۩  Background ۩๑▬▬▬▬▬●
export BACK_RESET='\e[49m'
export BACK_BLACK='\e[40m'
export BACK_WHITE='\e[107m'
export BACK_BLUE_DARK='\e[34m'
export BACK_BLUE_LIGHT='\e[104m'
export BACK_CYAN_DARK='\e[46m'
export BACK_CYAN_LIGHT='\e[106m'
export BACK_GRAY_DARK='\e[100m'
export BACK_GRAY_LIGHT='\e[47m'
export BACK_GREEN_DARK='\e[42m'
export BACK_GREEN_LIGHT='\e[102m'
export BACK_MAGENTA_DARK='\e[45m'
export BACK_MAGENTA_LIGHT='\e[105m'
export BACK_RED_DARK='\e[41m'
export BACK_RED_LIGHT='\e[101m'
export BACK_YELLOW_DARK='\e[43m'
export BACK_YELLOW_LIGHT='\e[103m'

# ●▬▬▬▬▬๑۩  Formats ۩๑▬▬▬▬▬●
export SET_BLINK='\e[5m'
export RESET_BLINK='\e[25m'
export SET_BOLD='\e[1m'
export RESET_BOLD='\e[21m'
export SET_BRIGHT='\e[1m'
export RESET_BRIGHT='\e[21m'
export SET_DIM='\e[2m'
export RESET_DIM='\e[22m'
export SET_HIDDEN='\e[8m'
export RESET_HIDDEN='\e[28m'
export SET_ITALIC='\e[3m'
export RESET_ITALIC='\e[23m'
export SET_REVERSE='\e[7m'
export RESET_REVERSE='\e[27m'
export SET_STRIKETHROUGH='\e[9m'
export RESET_STRIKETHROUGH='\e[29m'
export SET_UNDERLINE='\e[4m'
export RESET_UNDERLINE='\e[24m'
export RESET_FULL='\e[0m'
