#!/bin/bash
# Original page: https://taskwarrior.org/docs/examples.html

echo -e "\e[3m\e[32mCreate a task:\e[0m \e[3m\$ task add \"Pay the rent\"\e[0m"
echo -e "\e[3m\e[33mCreate a task with due date:\e[0m \e[3m\$ task add \"Pay the rent\" due:eom\e[0m"
echo -e "\e[3m\e[32mAdd a due date to a task:\e[0m \e[3m\$ task 1 modify due:eom\e[0m"
echo -e "\e[3m\e[33mRemove a due date from a task:\e[0m \e[3m\$ task 1 modify due:\e[0m"
echo -e "\e[3m\e[32mCreate a task with a multiline description:\e[0m \e[3m\$ task add \"Pay the rent.
                                              Pay the bills.
                                              Invite your Chrissy to a dinner.\""
echo -e "\e[3m\e[33mCreate a task with a project:\e[0m \e[3m\$ task add \"Pay the rent\" project:personal\e[0m"
echo -e "\e[3m\e[32mMoving all tasks to a new project.:\e[0m \e[3m\$ task project:OLDNAME modify project:NEWNAME\e[0m"
echo -e "\e[3m\e[33mMoving all pending tasks to a new project.:\e[0m \e[3m\$ task project:OLDNAME and status:pending modify project:NEWNAME\e[0m"
echo -e "\e[3m\e[32mList projects in use:\e[0m \e[3m\$ task projects\e[0m"
echo -e "\e[3m\e[33mList tags in use:\e[0m \e[3m\$ task +TAGNAME list\e[0m"
