#!/usr/bin/env php
<?php

class Helper {

    static private function __makeSeed()
    {
        list($usec, $sec) = explode(' ', microtime());
        srand($sec + $usec * 1000000);
    }

    public function random($max, $min = 0){
        self::__makeSeed();

        if(is_array($max))
        {
            return $max[rand($min, count($max) -1)];
        }
        if(is_int($max))
        {
            return rand($min,$max);
        }
        throw new InvalidArgumentException("[Helper::random] The \$max argument must be an array or an integer.");
    }
}

class Data
{
    static public function actions()
    {
        $data = array(  array("accepts", 1),
                        array("adds", 0),
                        array("admires", 1),
                        array("admits", 0),
                        array("advises", 1),
                        array("affords", 0),
                        array("agrees", 0),
                        array("alerts", 1),
                        array("allows", 0),
                        array("amuses", 1),
                        array("analyses", 1),
                        array("annoies", 1),
                        array("announces", 1),
                        array("answers", 1),
                        array("apologises", 0),
                        array("appears", 0),
                        array("applauds", 1),
                        array("appreciates", 1),
                        array("approves", 1),
                        array("argues", 0),
                        array("arranges", 0),
                        array("arrests", 1),
                        array("arrives", 0),
                        array("asks", 0),
                        array("attaches", 0),
                        array("attacks", 1),
                        array("attempts", 0),
                        array("attends", 0),
                        array("attracts", 1),
                        array("avoids", 1),
                        array("backs", 0),
                        array("bakes", 1),
                        array("balances", 1),
                        array("bangs", 1),
                        array("bans", 1),
                        array("bares", 0),
                        array("bathes", 1),
                        array("bats", 0),
                        array("battles", 1),
                        array("beams", 1),
                        array("begs", 0),
                        array("behaves", 0),
                        array("belongs", 0),
                        array("bleaches", 1),
                        array("bless", 1),
                        array("blinds", 1),
                        array("blinks", 0),
                        array("blots", 0),
                        array("blushes", 0),
                        array("boasts", 0),
                        array("boils", 1),
                        array("bolts", 0),
                        array("bombs", 1),
                        array("books", 0),
                        array("bores", 1),
                        array("borrows", 0),
                        array("bounces", 0),
                        array("bows", 0),
                        array("boxes", 0),
                        array("brakes", 0),
                        array("branches", 0),
                        array("breathes", 0),
                        array("(BrE)s", 0),
                        array("bruises", 1),
                        array("brushes", 1),
                        array("bubbles", 1),
                        array("bumps", 1),
                        array("buries", 1),
                        array("burns", 1),
                        array("buzzes", 1),
                        array("calculates", 1),
                        array("calls", 1),
                        array("camps", 0),
                        array("cares", 0),
                        array("carries", 1),
                        array("carves", 1),
                        array("causes", 0),
                        array("challenges", 1),
                        array("changes", 1),
                        array("charges", 1),
                        array("chases", 1),
                        array("cheats", 1),
                        array("checks", 0),
                        array("cheers", 1),
                        array("chews", 0),
                        array("chokes", 1),
                        array("chops", 1),
                        array("claims", 1),
                        array("claps", 0),
                        array("cleans", 1),
                        array("clears", 1),
                        array("clips", 1),
                        array("closes", 1),
                        array("coaches", 1),
                        array("coils", 0),
                        array("collects", 0),
                        array("colours", 1),
                        array("combs", 1),
                        array("commands", 1),
                        array("communicates", 0),
                        array("compares", 1),
                        array("competes", 0),
                        array("complains", 0),
                        array("completes", 1),
                        array("concentrates", 0),
                        array("concerns", 1),
                        array("confesses", 0),
                        array("confuses", 1),
                        array("connects", 0),
                        array("considers", 1),
                        array("consists", 0),
                        array("contains", 1),
                        array("continues", 1),
                        array("copies", 1),
                        array("corrects", 1),
                        array("coughs", 1),
                        array("counts", 1),
                        array("covers", 1),
                        array("cracks", 1),
                        array("crashes", 1),
                        array("crawls", 0),
                        array("cries", 0),
                        array("crosses", 0),
                        array("crushes", 1),
                        array("cures", 1),
                        array("curls", 1),
                        array("curves", 0),
                        array("cycles", 0),
                        array("damages", 1),
                        array("dams", 1),
                        array("dances", 0),
                        array("dares", 0),
                        array("decaies", 1),
                        array("deceives", 1),
                        array("decides", 0),
                        array("decorates", 1),
                        array("delaies", 0),
                        array("delights", 1),
                        array("delivers", 1),
                        array("depends", 0),
                        array("describes", 1),
                        array("deserts", 0),
                        array("deserves", 1),
                        array("destroies", 0),
                        array("detects", 1),
                        array("develops", 1),
                        array("disagrees", 0),
                        array("disappears", 0),
                        array("disapproves", 1),
                        array("disarms", 1),
                        array("discovers", 1),
                        array("dislikes", 1),
                        array("divides", 1),
                        array("doubles", 0),
                        array("doubts", 0),
                        array("drags", 1),
                        array("drains", 1),
                        array("dreams", 0),
                        array("dresses", 1),
                        array("dries", 1),
                        array("drips", 1),
                        array("drops", 1),
                        array("drowns", 0),
                        array("drums", 0),
                        array("dusts", 0),
                        array("earns", 1),
                        array("educates", 1),
                        array("embarrasses", 1),
                        array("emploies", 1),
                        array("empties", 1),
                        array("encourages", 1),
                        array("ends", 1),
                        array("enjoies", 1),
                        array("enters", 1),
                        array("entertains", 1),
                        array("escapes", 1),
                        array("examines", 1),
                        array("excites", 1),
                        array("excuses", 1),
                        array("exercises", 1),
                        array("exists", 0),
                        array("expands", 1),
                        array("expects", 1),
                        array("explains", 1),
                        array("explodes", 1),
                        array("extends", 1),
                        array("faces", 1),
                        array("fades", 1),
                        array("fails", 1),
                        array("fancies", 1),
                        array("fastens", 0),
                        array("faxes", 1),
                        array("fears", 1),
                        array("fences", 1),
                        array("fetches", 1),
                        array("files", 1),
                        array("fills", 1),
                        array("films", 1),
                        array("fires", 1),
                        array("fits", 1),
                        array("fixes", 1),
                        array("flaps", 1),
                        array("flashes", 1),
                        array("floats", 0),
                        array("floods", 0),
                        array("flowers", 0),
                        array("flows", 0),
                        array("folds", 1),
                        array("follows", 1),
                        array("fools", 1),
                        array("forces", 1),
                        array("forms", 1),
                        array("founds", 0),
                        array("frames", 0),
                        array("fries", 1),
                        array("frightens", 1),
                        array("gathers", 0),
                        array("gazes", 1),
                        array("glows", 1),
                        array("glues", 1),
                        array("grabs", 1),
                        array("grates", 1),
                        array("greases", 1),
                        array("greets", 1),
                        array("grins", 0),
                        array("grips", 0),
                        array("groans", 0),
                        array("guarantees", 0),
                        array("guards", 1),
                        array("guesses", 0),
                        array("guides", 1),
                        array("hammers", 1),
                        array("handle", 1),
                        array("hands", 1),
                        array("hangs", 1),
                        array("happens", 0),
                        array("harasses", 1),
                        array("harms", 1),
                        array("hates", 1),
                        array("haunts", 1),
                        array("heads", 1),
                        array("heals", 1),
                        array("heaps", 1),
                        array("heats", 1),
                        array("helps", 1),
                        array("hooks", 1),
                        array("hopes", 0),
                        array("hops", 0),
                        array("hovers", 0),
                        array("hugs", 0),
                        array("hums", 0),
                        array("hunts", 1),
                        array("hurries", 0),
                        array("identifies", 1),
                        array("ignores", 1),
                        array("imagines", 1),
                        array("impresses", 1),
                        array("improves", 1),
                        array("includes", 1),
                        array("increases", 1),
                        array("influences", 1),
                        array("informs", 1),
                        array("injects", 0),
                        array("injures", 1),
                        array("instructs", 1),
                        array("intends", 0),
                        array("interests", 1),
                        array("interferes", 0),
                        array("interrupts", 1),
                        array("introduces", 1),
                        array("invents", 1),
                        array("invites", 1),
                        array("irritates", 1),
                        array("itches", 1),
                        array("jails", 0),
                        array("jams", 0),
                        array("jogs", 0),
                        array("joins", 0),
                        array("jokes", 0),
                        array("judges", 1),
                        array("juggles", 0),
                        array("jumps", 0),
                        array("kicks", 1),
                        array("kills", 1),
                        array("kisses", 1),
                        array("kneels", 0),
                        array("knits", 0),
                        array("knocks", 1),
                        array("knots", 0),
                        array("labels", 1),
                        array("lands", 0),
                        array("lasts", 0),
                        array("laughs", 0),
                        array("launches", 0),
                        array("learns", 0),
                        array("levels", 0),
                        array("licenses", 0),
                        array("licks", 1),
                        array("lies", 0),
                        array("lightens", 0),
                        array("likes", 1),
                        array("listens", 0),
                        array("lists", 0),
                        array("lives", 0),
                        array("loads", 0),
                        array("locks", 0),
                        array("longs", 0),
                        array("looks", 0),
                        array("loves", 0),
                        array("manages", 1),
                        array("mans", 1),
                        array("marches", 0),
                        array("marks", 1),
                        array("marries", 1),
                        array("matches", 0),
                        array("mates", 1),
                        array("matters", 0),
                        array("measures", 1),
                        array("meddles", 0),
                        array("melts", 1),
                        array("memorises", 1),
                        array("mends", 0),
                        array("messes", 0),
                        array("milks", 1),
                        array("mines", 0),
                        array("misses", 1),
                        array("mixes", 0),
                        array("moans", 0),
                        array("moors", 0),
                        array("mourns", 0),
                        array("moves", 0),
                        array("muddles", 0),
                        array("mugs", 0),
                        array("multiplies", 0),
                        array("murders", 0),
                        array("nails", 1),
                        array("names", 0),
                        array("needs", 1),
                        array("nests", 1),
                        array("nods", 0),
                        array("notes", 0),
                        array("notices", 1),
                        array("numbers", 0),
                        array("obeies", 1),
                        array("objects", 1),
                        array("observes", 1),
                        array("obtains", 1),
                        array("occurs", 0),
                        array("offends", 1),
                        array("offers", 0),
                        array("opens", 1),
                        array("orders", 1),
                        array("overflows", 0),
                        array("owes", 0),
                        array("owns", 1),
                        array("packs", 0),
                        array("paddles", 0),
                        array("paints", 1),
                        array("parks", 0),
                        array("parts", 0),
                        array("passes", 0),
                        array("pastes", 0),
                        array("pats", 0),
                        array("pauses", 0),
                        array("pecks", 0),
                        array("pedals", 0),
                        array("peels", 0),
                        array("peeps", 0),
                        array("performs", 0),
                        array("permits", 0),
                        array("phones", 1),
                        array("picks", 1),
                        array("pinches", 1),
                        array("pines", 0),
                        array("places", 0),
                        array("plaies", 0),
                        array("plans", 0),
                        array("plants", 1),
                        array("pleases", 1),
                        array("plugs", 1),
                        array("points", 1),
                        array("pokes", 1),
                        array("polishes", 1),
                        array("pops", 1),
                        array("possesses", 1),
                        array("posts", 0),
                        array("pours", 0),
                        array("practices", 0),
                        array("practises", 0),
                        array("praies", 0),
                        array("preaches", 0),
                        array("precedes", 1),
                        array("prefers", 1),
                        array("prepares", 1),
                        array("presents", 1),
                        array("preserves", 1),
                        array("presses", 0),
                        array("pretends", 0),
                        array("prevents", 0),
                        array("pricks", 0),
                        array("prints", 1),
                        array("produces", 1),
                        array("programs", 0),
                        array("promises", 1),
                        array("protects", 1),
                        array("provides", 1),
                        array("pulls", 1),
                        array("pumps", 1),
                        array("punches", 1),
                        array("punctures", 0),
                        array("punishes", 1),
                        array("pushes", 1),
                        array("questions", 1),
                        array("queues", 0),
                        array("races", 1),
                        array("radiates", 0),
                        array("rains", 0),
                        array("raises", 0),
                        array("reaches", 0),
                        array("realises", 0),
                        array("receives", 1),
                        array("recognises", 0),
                        array("records", 0),
                        array("reduces", 0),
                        array("reflects", 0),
                        array("refuses", 0),
                        array("regrets", 1),
                        array("reigns", 0),
                        array("rejects", 1),
                        array("rejoices", 0),
                        array("relaxes", 0),
                        array("releases", 0),
                        array("relies", 0),
                        array("remains", 0),
                        array("remembers", 1),
                        array("reminds", 1),
                        array("removes", 1),
                        array("repairs", 1),
                        array("repeats", 0),
                        array("replaces", 1),
                        array("replies", 0),
                        array("reports", 0),
                        array("reproduces", 1),
                        array("requests", 1),
                        array("rescues", 1),
                        array("retires", 0),
                        array("returns", 1),
                        array("rhymes", 0),
                        array("rinses", 0),
                        array("risks", 0),
                        array("robs", 1),
                        array("rocks", 1),
                        array("rolls", 1),
                        array("rots", 0),
                        array("rubs", 1),
                        array("ruins", 1),
                        array("rules", 1),
                        array("rushes", 1),
                        array("sacks", 0),
                        array("sails", 0),
                        array("satisfies", 1),
                        array("saves", 1),
                        array("saws", 1),
                        array("scares", 1),
                        array("scatters", 1),
                        array("scolds", 0),
                        array("scorches", 1),
                        array("scrapes", 1),
                        array("scratches", 1),
                        array("screams", 0),
                        array("screws", 1),
                        array("scribbles", 0),
                        array("scrubs", 0),
                        array("seals", 1),
                        array("searches", 1),
                        array("separates", 1),
                        array("serves", 1),
                        array("settles", 0),
                        array("shades", 0),
                        array("shares", 1),
                        array("shaves", 1),
                        array("shelters", 0),
                        array("shivers", 0),
                        array("shocks", 0),
                        array("shops", 0),
                        array("shrugs", 0),
                        array("sighs", 0),
                        array("signals", 1),
                        array("signs", 0),
                        array("sins", 0),
                        array("sips", 0),
                        array("skips", 0),
                        array("skis", 0),
                        array("slaps", 1),
                        array("slips", 1),
                        array("slows", 1),
                        array("smashes", 1),
                        array("smells", 1),
                        array("smiles", 0),
                        array("smokes", 0),
                        array("snatches", 0),
                        array("sneezes", 0),
                        array("sniffs", 1),
                        array("snores", 0),
                        array("snows", 0),
                        array("soaks", 0),
                        array("soothes", 0),
                        array("sounds", 0),
                        array("spares", 0),
                        array("sparkles", 0),
                        array("sparks", 0),
                        array("spells", 0),
                        array("spills", 1),
                        array("spoils", 0),
                        array("spots", 0),
                        array("spraies", 0),
                        array("sprouts", 0),
                        array("squashes", 1),
                        array("squeaks", 0),
                        array("squeals", 0),
                        array("squeezes", 0),
                        array("staies", 0),
                        array("stains", 1),
                        array("stamps", 0),
                        array("stares", 0),
                        array("starts", 0),
                        array("steers", 0),
                        array("steps", 0),
                        array("stirs", 0),
                        array("stitches", 0),
                        array("stops", 1),
                        array("stores", 0),
                        array("straps", 0),
                        array("strengthens", 0),
                        array("stretches", 0),
                        array("strips", 0),
                        array("strokes", 1),
                        array("stuffs", 0),
                        array("subtracts", 0),
                        array("succeeds", 0),
                        array("sucks", 1),
                        array("suffers", 0),
                        array("suggests", 0),
                        array("suits", 0),
                        array("supplies", 0),
                        array("supports", 1),
                        array("supposes", 0),
                        array("surprises", 1),
                        array("surrounds", 0),
                        array("suspects", 0),
                        array("suspends", 0),
                        array("switches", 0),
                        array("talks", 0),
                        array("tames", 1),
                        array("taps", 1),
                        array("tastes", 1),
                        array("teases", 1),
                        array("telephones", 1),
                        array("tempts", 0),
                        array("terrifies", 1),
                        array("tests", 1),
                        array("thanks", 0),
                        array("thaws", 0),
                        array("tickles", 1),
                        array("ticks", 0),
                        array("ties", 1),
                        array("times", 0),
                        array("tips", 0),
                        array("tires", 0),
                        array("touches", 1),
                        array("tours", 0),
                        array("tows", 0),
                        array("traces", 0),
                        array("trades", 0),
                        array("trains", 0),
                        array("transports", 0),
                        array("traps", 0),
                        array("travels", 0),
                        array("treats", 0),
                        array("trembles", 0),
                        array("tricks", 0),
                        array("tries", 1),
                        array("trips", 0),
                        array("trots", 0),
                        array("troubles", 0),
                        array("trusts", 1),
                        array("tugs", 0),
                        array("tumbles", 0),
                        array("turns", 0),
                        array("twists", 0),
                        array("types", 0),
                        array("undresses", 1),
                        array("unfastens", 0),
                        array("unites", 0),
                        array("unlocks", 0),
                        array("unpacks", 0),
                        array("untidies", 0),
                        array("ups", 0),
                        array("uses", 1),
                        array("vanishes", 0),
                        array("visits", 1),
                        array("wails", 0),
                        array("waits", 0),
                        array("walks", 0),
                        array("wanders", 0),
                        array("wants", 1),
                        array("warms", 0),
                        array("warns", 0),
                        array("washes", 1),
                        array("wastes", 1),
                        array("watches", 0),
                        array("waters", 0),
                        array("waves", 0),
                        array("weighs", 1),
                        array("welcomes", 1),
                        array("whines", 0),
                        array("whips", 1),
                        array("whirls", 0),
                        array("whispers", 0),
                        array("whistles", 0),
                        array("winks", 0),
                        array("wipes", 0),
                        array("wishes", 1),
                        array("wobbles", 0),
                        array("wonders", 0),
                        array("works", 0),
                        array("worries", 0),
                        array("wraps", 1),
                        array("wrecks", 0),
                        array("wrestles", 0),
                        array("wriggles", 0),
                        array("x-raies", 1),
                        array("yawns", 0),
                        array("yells", 0),
                        array("zips", 0),
                        array("zooms", 1));
        return Helper::random($data);
    }

    static public function adverbs()
    {
        $data = array(   "abnormally",
                            "aboard",
                            "about",
                            "abroad",
                            "absentmindedly",
                            "absolutely",
                            "abundantly",
                            "accidentally",
                            "accordingly",
                            "actively",
                            "actually",
                            "acutely",
                            "admiringly",
                            "affectionately",
                            "affirmatively",
                            "after",
                            "afterwards",
                            "agreeably",
                            "almost",
                            "already",
                            "always",
                            "amazingly",
                            "angrily",
                            "annoyingly",
                            "annually",
                            "anxiously",
                            "anyhow",
                            "anyplace",
                            "anyway",
                            "anywhere",
                            "appreciably",
                            "appropriately",
                            "around",
                            "arrogantly",
                            "aside",
                            "assuredly",
                            "astonishingly",
                            "away",
                            "awfully",
                            "awkwardly",
                            "badly",
                            "barely",
                            "bashfully",
                            "beautifully",
                            "before",
                            "begrudgingly",
                            "believably",
                            "bewilderedly",
                            "bewilderingly",
                            "bitterly",
                            "bleakly",
                            "blindly",
                            "blissfully",
                            "boastfully",
                            "boldly",
                            "boldly",
                            "boyishly",
                            "bravely",
                            "briefly",
                            "brightly",
                            "brilliantly",
                            "briskly",
                            "brutally",
                            "busily",
                            "calmly",
                            "candidly",
                            "carefully",
                            "carelessly",
                            "casually",
                            "cautiously",
                            "certainly",
                            "charmingly",
                            "cheerfully",
                            "chiefly",
                            "childishly",
                            "cleanly",
                            "clearly",
                            "cleverly",
                            "closely",
                            "cloudily",
                            "clumsily",
                            "coaxingly",
                            "coincidentally",
                            "coldly",
                            "colorfully",
                            "comfortably",
                            "commonly",
                            "compactly",
                            "compassionately",
                            "completely",
                            "confusedly",
                            "consequently",
                            "considerably",
                            "considerately",
                            "consistently",
                            "constantly",
                            "continually",
                            "continuously",
                            "coolly",
                            "correctly",
                            "courageously",
                            "covertly",
                            "cowardly",
                            "crazily",
                            "crossly",
                            "cruelly",
                            "cunningly",
                            "curiously",
                            "currently",
                            "customarily",
                            "cutely",
                            "daily",
                            "daintily",
                            "dangerously",
                            "daringly",
                            "darkly",
                            "dastardly",
                            "dearly",
                            "decently",
                            "deeply",
                            "defiantly",
                            "deftly",
                            "deliberately",
                            "delicately",
                            "delightfully",
                            "densely",
                            "diagonally",
                            "differently",
                            "diligently",
                            "dimly",
                            "directly",
                            "disorderly",
                            "divisively",
                            "docilely",
                            "dopily",
                            "doubtfully",
                            "down",
                            "dramatically",
                            "dreamily",
                            "during",
                            "eagerly",
                            "early",
                            "earnestly",
                            "easily",
                            "efficiently",
                            "effortlessly",
                            "elaborately",
                            "elegantly",
                            "eloquently",
                            "elsewhere",
                            "emotionally",
                            "endlessly",
                            "energetically",
                            "enjoyably",
                            "enormously",
                            "enough",
                            "enthusiastically",
                            "entirely",
                            "equally",
                            "especially",
                            "essentially",
                            "eternally",
                            "ethically",
                            "even",
                            "evenly",
                            "eventually",
                            "evermore",
                            "every",
                            "everywhere",
                            "evidently",
                            "evocatively",
                            "exactly",
                            "exceedingly",
                            "exceptionally",
                            "excitedly",
                            "exclusively",
                            "explicitly",
                            "expressly",
                            "extensively",
                            "externally",
                            "extra",
                            "extraordinarily",
                            "extremely",
                            "fairly",
                            "faithfully",
                            "famously",
                            "far",
                            "fashionably",
                            "fast",
                            "fatally",
                            "favorably",
                            "ferociously",
                            "fervently",
                            "fiercely",
                            "fiery",
                            "finally",
                            "financially",
                            "finitely",
                            "fluently",
                            "fondly",
                            "foolishly",
                            "forever",
                            "formally",
                            "formerly",
                            "fortunately",
                            "forward",
                            "frankly",
                            "frantically",
                            "freely",
                            "frenetically",
                            "frequently",
                            "fully",
                            "furiously",
                            "furthermore",
                            "generally",
                            "generously",
                            "gently",
                            "genuinely",
                            "genuinely",
                            "girlishly",
                            "gladly",
                            "gleefully",
                            "gracefully",
                            "graciously",
                            "gradually",
                            "gratefully",
                            "greatly",
                            "greedily",
                            "grimly",
                            "grudgingly",
                            "habitually",
                            "half-heartedly",
                            "handily",
                            "handsomely",
                            "haphazardly",
                            "happily",
                            "harmoniously",
                            "harshly",
                            "hastily",
                            "hastily",
                            "hatefully",
                            "hauntingly",
                            "healthily",
                            "heartily",
                            "heavily",
                            "helpfully",
                            "hence",
                            "highly",
                            "hitherto",
                            "honestly",
                            "hopelessly",
                            "horizontally",
                            "hourly",
                            "how",
                            "however",
                            "hugely",
                            "humorously",
                            "hungrily",
                            "hurriedly",
                            "hysterically",
                            "icily",
                            "identifiably",
                            "idiotically",
                            "imaginatively",
                            "immeasurably",
                            "immediately",
                            "immensely",
                            "impatiently",
                            "impressively",
                            "inappropriately",
                            "incessantly",
                            "incorrectly",
                            "indeed",
                            "independently",
                            "indoors",
                            "indubitably",
                            "inevitably",
                            "infinitely",
                            "informally",
                            "infrequently",
                            "innocently",
                            "inquisitively",
                            "instantly",
                            "intelligently",
                            "intensely",
                            "intently",
                            "interestingly",
                            "intermittently",
                            "internally",
                            "invariably",
                            "invisibly",
                            "inwardly",
                            "ironically",
                            "irrefutably",
                            "irritably",
                            "jaggedly",
                            "jauntily",
                            "jealously",
                            "jovially",
                            "joyfully",
                            "joylessly",
                            "joyously",
                            "jubilantly",
                            "judgmentally",
                            "just",
                            "justly",
                            "keenly",
                            "kiddingly",
                            "kindheartedly",
                            "kindly",
                            "knavishly",
                            "knottily",
                            "knowingly",
                            "knowledgeably",
                            "kookily",
                            "lastly",
                            "late",
                            "lately",
                            "later",
                            "lazily",
                            "less",
                            "lightly",
                            "likely",
                            "limply",
                            "lithely",
                            "lively",
                            "loftily",
                            "longingly",
                            "loosely",
                            "loudly",
                            "lovingly",
                            "loyally",
                            "luckily",
                            "luxuriously",
                            "madly",
                            "magically",
                            "mainly",
                            "majestically",
                            "markedly",
                            "materially",
                            "meaningfully",
                            "meanly",
                            "meantime",
                            "meanwhile",
                            "measurably",
                            "mechanically",
                            "medically",
                            "menacingly",
                            "merely",
                            "merrily",
                            "methodically",
                            "mightily",
                            "miserably",
                            "mockingly",
                            "monthly",
                            "morally",
                            "more",
                            "moreover",
                            "mortally",
                            "mostly",
                            "much",
                            "mysteriously",
                            "nastily",
                            "naturally",
                            "naughtily",
                            "nearby",
                            "nearly",
                            "neatly",
                            "needily",
                            "negatively",
                            "nervously",
                            "never",
                            "nevertheless",
                            "next",
                            "nicely",
                            "nightly",
                            "noisily",
                            "normally",
                            "nosily",
                            "not",
                            "now",
                            "nowadays",
                            "numbly",
                            "obediently",
                            "obligingly",
                            "obnoxiously",
                            "obviously",
                            "occasionally",
                            "oddly",
                            "offensively",
                            "officially",
                            "often",
                            "ominously",
                            "once",
                            "only",
                            "openly",
                            "optimistically",
                            "orderly",
                            "ordinarily",
                            "outdoors",
                            "outrageously",
                            "outwardly",
                            "outwards",
                            "overconfidently",
                            "overseas",
                            "painfully",
                            "painlessly",
                            "paradoxically",
                            "partially",
                            "particularly",
                            "passionately",
                            "patiently",
                            "perfectly",
                            "periodically",
                            "perpetually",
                            "persistently",
                            "personally",
                            "persuasively",
                            "physically",
                            "plainly",
                            "playfully",
                            "poetically",
                            "poignantly",
                            "politely",
                            "poorly",
                            "positively",
                            "possibly",
                            "potentially",
                            "powerfully",
                            "presently",
                            "presumably",
                            "prettily",
                            "previously",
                            "primly",
                            "principally",
                            "probably",
                            "promptly",
                            "properly",
                            "proudly",
                            "punctually",
                            "puzzlingly",
                            "quaintly",
                            "queasily",
                            "questionably",
                            "questioningly",
                            "quicker",
                            "quickly",
                            "quietly",
                            "quirkily",
                            "quite",
                            "quizzically",
                            "randomly",
                            "rapidly",
                            "rarely",
                            "readily",
                            "really",
                            "reasonably",
                            "reassuringly",
                            "recently",
                            "recklessly",
                            "regularly",
                            "reliably",
                            "reluctantly",
                            "remarkably",
                            "repeatedly",
                            "reponsibly",
                            "reproachfully",
                            "resentfully",
                            "respectably",
                            "respectfully",
                            "restfully",
                            "richly",
                            "ridiculously",
                            "righteously",
                            "rightfully",
                            "rightly",
                            "rigidly",
                            "roughly",
                            "routinely",
                            "rudely",
                            "ruthlessly",
                            "sadly",
                            "safely",
                            "scarcely",
                            "scarily",
                            "scientifically",
                            "searchingly",
                            "secretively",
                            "securely",
                            "sedately",
                            "seemingly",
                            "seldom",
                            "selfishly",
                            "selflessly",
                            "separately",
                            "seriously",
                            "shakily",
                            "shamelessly",
                            "sharply",
                            "sheepishly",
                            "shoddily",
                            "shortly",
                            "shrilly",
                            "shyly",
                            "significantly",
                            "silently",
                            "silicitiously",
                            "simply",
                            "sincerely",
                            "singularly",
                            "skillfully",
                            "sleepily",
                            "slightly",
                            "slowly",
                            "slyly",
                            "smoothly",
                            "so",
                            "softly",
                            "solely",
                            "solemnly",
                            "solidly",
                            "somehow",
                            "sometimes",
                            "somewhat",
                            "somewhere",
                            "soon",
                            "spasmodically",
                            "specially",
                            "specifically",
                            "spectacularly",
                            "speedily",
                            "spiritually",
                            "splendidly",
                            "sporadically",
                            "startlingly",
                            "steadily",
                            "stealthily",
                            "sternly",
                            "still",
                            "strenuously",
                            "stressfully",
                            "strictly",
                            "structurally",
                            "studiously",
                            "stupidly",
                            "stylishly",
                            "subsequently",
                            "substantially",
                            "subtly",
                            "successfully",
                            "suddenly",
                            "sufficiently",
                            "suitably",
                            "superficially",
                            "supremely",
                            "surely",
                            "surprisingly",
                            "suspiciously",
                            "sweetly",
                            "swiftly",
                            "sympathetically",
                            "systematically",
                            "temporarily",
                            "tenderly",
                            "tensely",
                            "tepidly",
                            "terribly",
                            "thankfully",
                            "then",
                            "there",
                            "thereby",
                            "thoroughly",
                            "thoughtfully",
                            "thus",
                            "tightly",
                            "today",
                            "together",
                            "tomorrow",
                            "too",
                            "totally",
                            "touchingly",
                            "tremendously",
                            "truly",
                            "truthfully",
                            "twice",
                            "ultimately",
                            "unabashedly",
                            "unanimously",
                            "unbearably",
                            "unbelievably",
                            "unemotionally",
                            "unethically",
                            "unexpectedly",
                            "unfailingly",
                            "unfavorably",
                            "unfortunately",
                            "uniformly",
                            "unilaterally",
                            "unimpressively",
                            "universally",
                            "unkindly",
                            "unnaturally",
                            "unnecessarily",
                            "unquestionably",
                            "unselfishly",
                            "unskillfully",
                            "unwillingly",
                            "up",
                            "upbeat",
                            "upliftingly",
                            "upright",
                            "upside-down",
                            "upward",
                            "upwardly",
                            "urgently",
                            "usefully",
                            "uselessly",
                            "usually",
                            "utterly",
                            "vacantly",
                            "vaguely",
                            "vainly",
                            "valiantly",
                            "vastly",
                            "verbally",
                            "vertically",
                            "very",
                            "viciously",
                            "victoriously",
                            "vigilantly",
                            "vigorously",
                            "violently",
                            "visibly",
                            "visually",
                            "vivaciously",
                            "voluntarily",
                            "warmly",
                            "weakly",
                            "wearily",
                            "weekly",
                            "well",
                            "wetly",
                            "when",
                            "where",
                            "while",
                            "whole-heartedly",
                            "wholly",
                            "why",
                            "wickedly",
                            "widely",
                            "wiggly",
                            "wildly",
                            "willfully",
                            "willingly",
                            "wisely",
                            "woefully",
                            "wonderfully",
                            "worriedly",
                            "worthily",
                            "wrongly",
                            "yearly",
                            "yearningly",
                            "yesterday",
                            "yet",
                            "youthfully",
                            "zanily",
                            "zealously",
                            "zestfully",
                            "zestily");
        return Helper::random($data);

    }

    static public function artists()
    {
        $data = array(  "Aaliyah",
                        "Adnan Ghalib",
                        "Adrianne Gonzalez",
                        "Adrienne Bailon",
                        "Aedin Adams",
                        "Ailee",
                        "Aileen Quinn",
                        "AJ Michalka",
                        "Akino",
                        "Alana Lee",
                        "Alanis Morissette",
                        "Alanna Ubach",
                        "Alexa Dectis",
                        "Ali Brustofski",
                        "Alisha",
                        "Alissa Moreno",
                        "Alycia Bellamy",
                        "Aly Michalka",
                        "Alyson",
                        "AM",
                        "Amber Liu",
                        "Amerie",
                        "Ana Matronic",
                        "Ana Rodríguez",
                        "Anastacia",
                        "Ana Victoria",
                        "Angel Taylor",
                        "Anna Kendrick",
                        "Anna Nalick",
                        "Anna Oxygen",
                        "Anna Rose Menken",
                        "Ann Barnes",
                        "Ann Crumb",
                        "Annie Lin",
                        "Ariana Grande",
                        "Ashlee Simpson",
                        "Ashley Tisdale",
                        "Asia Nitollano",
                        "Aubrey Logan",
                        "Aubrey O'Day",
                        "Aundrea Fimbres",
                        "Aurora Alluria",
                        "Austin Mahone",
                        "Bailey Jay",
                        "Barbra Streisand",
                        "Beckah Shae",
                        "Becky G.",
                        "Belinda Carlisle",
                        "Bella Thorne",
                        "Be Myself",
                        "Ben Bledsoe",
                        "Ben Folds",
                        "Benjamin Keough",
                        "Beth Anderson",
                        "Bette Midler",
                        "Bettina Bush",
                        "Beverly Lee",
                        "Beyoncé Knowles",
                        "Billy Joel",
                        "Blaire Reinhard",
                        "B.o.B.",
                        "Bobby Brown",
                        "Bobby Edner",
                        "Bonnie McKee",
                        "Booboo Stewart",
                        "Borns",
                        "Brandi Emma",
                        "Brenda Reid",
                        "Brian Littrell",
                        "Bridgit Mendler",
                        "Brielle Biermann",
                        "Britney Spears",
                        "Brittani Senser",
                        "Brittany Smith",
                        "Britt Nicole",
                        "Brooke Annibale",
                        "Brooke Hogan",
                        "Cady Groves",
                        "Calling All Lovers",
                        "Camila Cabello",
                        "Camryn",
                        "Cara Jones",
                        "Carly Simon",
                        "Carmit Bachar",
                        "Carole Davis",
                        "Carole King",
                        "Casey Desmond",
                        "Cass Elliot",
                        "Cassie Ventura",
                        "Cáthia",
                        "CeCe Frey",
                        "Ce Ce Peniston",
                        "Chanté Moore",
                        "Cher",
                        "Chris Brown",
                        "Chris Crocker",
                        "Christina Aguilera",
                        "Christina Milian",
                        "Chris Wallace",
                        "Ciara",
                        "Clairity",
                        "Claudine Longet",
                        "Clay Aiken",
                        "Colbie Caillat",
                        "Colette Carr",
                        "Connie Francis",
                        "Corbin Bleu",
                        "Cori Yarckin",
                        "Craig Crippen",
                        "Crystal Bowersox",
                        "Cyndi Lauper",
                        "Dana Mase",
                        "Danielle Brisebois",
                        "Dani Siciliano",
                        "Danny Keough",
                        "Daphne Blunt",
                        "Daphne Willis",
                        "David Archuleta",
                        "David Daniel Hudson",
                        "David Hasselhoff",
                        "Daya",
                        "Debbie Harry",
                        "Debbie Reynolds",
                        "Debby Boone",
                        "Demi Lovato",
                        "Devyn Rose",
                        "Diana Ross",
                        "Dionne Warwick",
                        "Divine",
                        "DJ Sennett",
                        "Dolly Parton",
                        "Donna Summer",
                        "Donny Osmond",
                        "Doris Day",
                        "Drake Bell",
                        "Dreezy",
                        "Eden xo Malakouti",
                        "Elizabeth Daily",
                        "Ellen Sandweiss",
                        "Ellie Greenwich",
                        "Emii",
                        "Emma Roberts",
                        "Eric Nam",
                        "Erika Van Pelt",
                        "Ethel Merman",
                        "Evelyn King",
                        "Feel",
                        "Fiona",
                        "Fiona Apple",
                        "FLAG",
                        "Forrest",
                        "Frankee",
                        "Frankie Valli",
                        "Gene Pitney",
                        "Gil Bernal",
                        "Gina Villalobos",
                        "Ginny Arnell",
                        "Gloria Estefan",
                        "Gwen Stefani",
                        "Haley Reinhart",
                        "Harriet Schock",
                        "Harry Connick Jr.",
                        "Hayley Williams",
                        "Haylie Duff",
                        "Helen Kane",
                        "Helen Reddy",
                        "Hilary Duff",
                        "Hildegarde",
                        "Huey Lewis",
                        "Hulk Hogan",
                        "Isabelle Nuru",
                        "Ivy Levan",
                        "Jaci Velasquez",
                        "Jack Griffo",
                        "Jackie Tohn",
                        "Jackson Browne",
                        "Jada",
                        "Jake Davis",
                        "Jana",
                        "Jane Badler",
                        "Janel Parrish",
                        "Janet Jackson",
                        "Jane Weintraub",
                        "Jasmine Sagginario",
                        "Jasmine Villegas",
                        "Jason Derulo",
                        "Jason Evigan",
                        "Jennifer Holliday",
                        "Jennifer Hudson",
                        "Jennifer Lopez",
                        "Jenn Korbee",
                        "Jerry Lee Lewis",
                        "Jessica Sanchez",
                        "Jessica Simpson",
                        "Jessica Sutta",
                        "Jill Corey",
                        "Jillian Wheeler",
                        "Jimmy Buffett",
                        "Joanna 'JoJo' Levesque",
                        "Joanna Stingray",
                        "Joey Heatherton",
                        "Joey Powers",
                        "Johnny Mathis",
                        "Jonnie and Brookie",
                        "Jordan Bratman",
                        "Jordan Fisher",
                        "Joyce Vincent Wilson",
                        "Joy Enriquez",
                        "Joy Villa",
                        "Kaci Battaglia",
                        "Kandice Melonakos",
                        "Karen Carpenter",
                        "Karen Young",
                        "Kate Smith",
                        "Katey Sagal",
                        "Kat Graham",
                        "Katharine McPhee",
                        "Kathy Young",
                        "Katrina Leskanich",
                        "Katrina Parker",
                        "Katy Perry",
                        "Kaya Stewart",
                        "Keedy",
                        "Keely Smith",
                        "Keke Palmer",
                        "Kelis",
                        "Kelley Jakle",
                        "Kelly Clarkson",
                        "Kelly Rowland",
                        "Kesha",
                        "Kevin Scott Richardson",
                        "Kevin Woo",
                        "Kiely Williams",
                        "Kimberly Wyatt",
                        "Kim Zolciak-Biermann",
                        "Kina Grannis",
                        "Kipp Hamilton",
                        "Kirsten Price",
                        "Kris Allen",
                        "Krissy Krissy",
                        "Kristin Chenoweth",
                        "Krystal Jung",
                        "Krystal Meyers",
                        "Lada St. Edmund",
                        "Lady Gaga",
                        "Lana Del Rey",
                        "Lane Caudell",
                        "Laura Rizzotto",
                        "Leah Dizon",
                        "Leah Kunkel",
                        "Lea Michele",
                        "LeAnn Rimes",
                        "Lea Sunshine",
                        "Leighton Meester",
                        "Leslie Carter",
                        "Letoya Luckett",
                        "Libby Holman",
                        "Lilián García",
                        "Lil Suzy",
                        "Linda Eder",
                        "Linda Hopper",
                        "Lindsay Lohan",
                        "Lisa Barbuscia",
                        "Lisa Bevill",
                        "Lisa Heller",
                        "Lisa Marie Presley",
                        "LuAnn D'Agostino",
                        "Lucia Cole",
                        "Lynn Davis",
                        "Madilyn Bailey",
                        "Madison Beer",
                        "Madonna",
                        "Malea McGuinness",
                        "Malese Jow",
                        "Malina Moye",
                        "Mandy Jiroux",
                        "Mandy Rain",
                        "Ma'Niche",
                        "Manika",
                        "Mariah Carey",
                        "Marié Digby",
                        "Marilyn Duke",
                        "Marilyn McCoo",
                        "Marilyn Wilson",
                        "Marisol Thomas",
                        "Marlene VerPlanck",
                        "Marsha A. Hunt",
                        "Martha Raye",
                        "Mathai",
                        "Meaghan Martin",
                        "Megan Lee",
                        "Meghan Trainor",
                        "Meiko",
                        "Melba Moore",
                        "Michael Alig",
                        "Michael Jackson",
                        "Michelle Branch",
                        "Michelle Lambert",
                        "Michelle Williams",
                        "Michiru Akiyoshi",
                        "Mike DelGuidice",
                        "Miki Ishikawa",
                        "Miley Cyrus",
                        "Miranda Cosgrove",
                        "Miss Amani",
                        "Miyoshi Umeki",
                        "Mona Lisa",
                        "Myah Marie",
                        "Myra",
                        "Natalie Cole",
                        "Neilson Hubbard",
                        "Nellie McKay",
                        "Nichkhun",
                        "Nicki Minaj",
                        "Nicole Scherzinger",
                        "Nicole Wray",
                        "Nikki Flores",
                        "Nikkole",
                        "No",
                        "Noosa",
                        "Nora Bayes",
                        "Norah Jones",
                        "Noreen Corcoran",
                        "Olivia",
                        "Olivia Holt",
                        "Olivia Olson",
                        "Olivia Somerlyn",
                        "Pamela Polland",
                        "Paris Hilton",
                        "Paris-Michael K. Jackson",
                        "Paris Smith",
                        "Pat Suzuki",
                        "Patti Dahlstrom",
                        "Patty Duke",
                        "Paula Abdul",
                        "Paul Anka",
                        "Paulina Gretzky",
                        "Paul Simon",
                        "Pee Wee",
                        "Perla Batalla",
                        "Peter Pou",
                        "Phil Campos",
                        "Phoebe Ryan",
                        "Phoenix",
                        "Pia Zadora",
                        "Pink",
                        "Places",
                        "Porcelain Black",
                        "P.P. Arnold",
                        "Prince Michael",
                        "Prince Michael II",
                        "QT",
                        "Rachael Yamagata",
                        "Raquel Castro",
                        "Raven-Symoné",
                        "Ray Smith",
                        "Rebecca Black",
                        "Regina Belle",
                        "Renee Sands",
                        "Richard Marx",
                        "Roberta Flack",
                        "Rob Hegel",
                        "Rob Thomas",
                        "Robyn Adele Anderson",
                        "Rockell",
                        "Rusty Hamer",
                        "Ryan Beatty",
                        "Ryan Starr",
                        "Sabrina Bryan",
                        "Samantha Cole",
                        "Sam Milby",
                        "Sam Tsui",
                        "Sandy Stewart",
                        "Sara Baiyu Chen",
                        "Sara Bareilles",
                        "Sarah Blacker",
                        "Sarah Buxton",
                        "Sara Niemietz",
                        "Sarine Voltage",
                        "Sasha Allen",
                        "Scarlett Johansson",
                        "Selena",
                        "Selena Gomez",
                        "Sevyn Streeter",
                        "Shannon Bex",
                        "Shealeigh",
                        "Shelley Fabares",
                        "Sheryl Crow",
                        "Sierra Kusterbeck",
                        "Sky Ferreira",
                        "Skylar Stecker",
                        "Sophie Beem",
                        "Stacey Swain",
                        "Stacie Orrico",
                        "Storm Calysta",
                        "Sue Lyon",
                        "Sunny",
                        "Susanna Hoffs",
                        "Susan Roshan",
                        "Suzi Quatro",
                        "Tae Brooks",
                        "Tamar Braxton",
                        "Tamela D'Amico",
                        "Tamyra Gray",
                        "Taryn Southern",
                        "Taylor Bright",
                        "Taylor Dayne",
                        "Taylor Swift",
                        "Teena Marie",
                        "Terra Naomi",
                        "That Poppy",
                        "Theresa Andersson",
                        "Tia Carrere",
                        "Tiara Thomas",
                        "Tiffany",
                        "Tiffany Brookes",
                        "Tiffany Houghton",
                        "Tightrope Walker",
                        "Tina Robin",
                        "Tinashe",
                        "Tina Turner",
                        "T Lopez",
                        "Tommy Sands",
                        "Toni Braxton",
                        "Tony Bennett",
                        "Tori Amos",
                        "Tor Miller",
                        "Toya Nash",
                        "Trish Thuy Trang",
                        "Uffie",
                        "Valentine Leone",
                        "Vanessa Carlton",
                        "Vanessa Curry",
                        "Vanessa Daou",
                        "Vanessa Hudgens",
                        "Vicki Vann",
                        "Victoria Acosta",
                        "Victoria Justice",
                        "Vikki Carr",
                        "Vitamin C",
                        "Wendy Starland",
                        "Whitney Houston",
                        "Whitney Wolanin",
                        "Willa Ford",
                        "William Hung",
                        "Willow Smith",
                        "Yulianna",
                        "Zaena Morisho",
                        "Zakiya",
                        "Zariah Avana",
                        "Zendaya",
                        "Zooey Deschanel");
        return Helper::random($data);
    }

    static public function superHeores()
    {
        $data = array( "Adam Strange",
                        "Agent Liberty",
                        "Air Wave",
                        "Amazo",
                        "Animal Man",
                        "Aqualad",
                        "Aquaman",
                        "Arsenal",
                        "Artemis of Bana-Mighdall",
                        "Atom Smasher",
                        "Aurakles",
                        "Azrael",
                        "Aztek",
                        "Bane",
                        "Barry Allen",
                        "Bart Allen",
                        "Batgirl",
                        "Batman",
                        "Batwing",
                        "Batwoman",
                        "Beast Boy",
                        "Black Canary",
                        "Black Lightning",
                        "Blue Beetle",
                        "Booster Gold",
                        "Brainiac",
                        "Bronze Tiger",
                        "B`wana Beast",
                        "Captain Atom",
                        "Captain Comet",
                        "Captain Marvel",
                        "Captain Metropolis",
                        "Cassandra Cain",
                        "Colossal Boy",
                        "Comedian",
                        "Cosmic Boy",
                        "Cyborg",
                        "Damian Wayne",
                        "Dan the Dyna-Mite",
                        "Deadman",
                        "Dick Grayson",
                        "Donna Troy",
                        "Dr. Fate",
                        "Dr. Manhattan",
                        "Elongated Man",
                        "Etrigan the Demon",
                        "Felicity Smoak",
                        "Ferro Lad",
                        "Fire",
                        "Firestorm",
                        "Gangbuster",
                        "Geo Force",
                        "Green Arrow",
                        "Green Arrow",
                        "Green Lantern",
                        "Grifter",
                        "Guardian",
                        "Guy Gardner",
                        "Gypsy",
                        "Hal Jordan",
                        "Hank Hall",
                        "Hawkgirl",
                        "Hawkman",
                        "Hooded Justice",
                        "Hourman",
                        "Huntress",
                        "Ice",
                        "Icemaiden",
                        "Impulse",
                        "Invisible Kid",
                        "Iris West",
                        "Jason Todd",
                        "Jayna",
                        "Jericho",
                        "Jesse Chambers",
                        "Jezebelle",
                        "John Constantine",
                        "Johnny Quick",
                        "John Stewart",
                        "Jonah Hex",
                        "Judomaster",
                        "Kamandi",
                        "Karate Kid",
                        "Katana",
                        "Katar Hol",
                        "Kate Spencer",
                        "Kent Shakespeare",
                        "Kid Flash",
                        "Kid Flash",
                        "Kid Flash",
                        "Kyle Rayner",
                        "Lagoon Boy",
                        "Laurie Jupiter",
                        "Liberty Belle",
                        "Lightning Lad",
                        "Manhunter",
                        "Martian Manhunter",
                        "Mary Marvel",
                        "Mas y Menos",
                        "Metal Men",
                        "Metamorpho",
                        "Misfit",
                        "Miss Martian",
                        "Mister America",
                        "Mister America",
                        "Mr. Terrific",
                        "Nightwing",
                        "Nite Owl",
                        "Nite Owl II",
                        "Obsidian",
                        "Oracle",
                        "Orin",
                        "Orion",
                        "Owlman",
                        "Owlwoman",
                        "Ozymandias",
                        "Pantha",
                        "Phantom Girl",
                        "Phantom Lady",
                        "Phantom Stranger",
                        "Plastic Man",
                        "Power Girl",
                        "Raven",
                        "Ray",
                        "Red Arrow",
                        "Red Tornado",
                        "Robin",
                        "Robotman",
                        "Rocket",
                        "Rocket Red",
                        "Rorschach",
                        "Roy Harper",
                        "Sandy Hawkins",
                        "Saturn Girl",
                        "Seven Soldiers of Victory",
                        "Shining Knight",
                        "Silk Spectre",
                        "Solomon Grundy",
                        "Spectre",
                        "Speedy",
                        "Starfire",
                        "Stargirl",
                        "Starman",
                        "Star-Spangled Kid",
                        "Static",
                        "Stephanie Brown",
                        "Superboy",
                        "Supergirl",
                        "Superman",
                        "Terra",
                        "Terry McGinnis",
                        "Tex Thompson",
                        "The Atom",
                        "The Flash",
                        "The Question",
                        "Tiger",
                        "Tim Drake",
                        "TNT",
                        "Tomorrow Woman",
                        "Triplicate Girl",
                        "Vibe",
                        "Vigilante",
                        "Vixen",
                        "Vulcan",
                        "Wally West",
                        "Wildcat",
                        "Wonder Girl",
                        "Wonder Woman",
                        "Zan",
                        "Zatanna",
                        "Zatara");
        return Helper::random($data);
    }

    static public function countries()
    {
        $data = array(  "Afghanistan",
                        "Albania",
                        "Algeria",
                        "Andorra",
                        "Angola",
                        "Antigua and Barbuda",
                        "Argentina",
                        "Armenia",
                        "Aruba",
                        "Australia",
                        "Austria",
                        "Azerbaijan",
                        "The Bahamas",
                        "Bahrain",
                        "Bangladesh",
                        "Barbados",
                        "Belarus",
                        "Belgium",
                        "Belize",
                        "Benin",
                        "Bhutan",
                        "Bolivia",
                        "Bosnia and Herzegovina",
                        "Botswana",
                        "Brazil",
                        "Brunei ",
                        "Bulgaria",
                        "Burkina Faso",
                        "Burma",
                        "Burundi",
                        "Cambodia",
                        "Cameroon",
                        "Canada",
                        "Cabo Verde",
                        "Central African Republic",
                        "Chad",
                        "Chile",
                        "China",
                        "Colombia",
                        "Comoros",
                        "Democratic Republic of the Congo",
                        "Republic of the Congo",
                        "Costa Rica",
                        "Cote d`Ivoire",
                        "Croatia",
                        "Cuba",
                        "Curacao",
                        "Cyprus",
                        "Czech Republic",
                        "Denmark",
                        "Djibouti",
                        "Dominica",
                        "Dominican Republic",
                        "Ecuador",
                        "Egypt",
                        "El Salvador",
                        "Equatorial Guinea",
                        "Eritrea",
                        "Estonia",
                        "Ethiopia",
                        "Fiji",
                        "Finland",
                        "France",
                        "Gabon",
                        "The Gambia",
                        "Georgia",
                        "Germany",
                        "Ghana",
                        "Greece",
                        "Grenada",
                        "Guatemala",
                        "Guinea",
                        "Guinea-Bissau",
                        "Guyana",
                        "Haiti",
                        "Holy See",
                        "Honduras",
                        "Hong Kong",
                        "Hungary",
                        "Iceland",
                        "India",
                        "Indonesia",
                        "Iran",
                        "Iraq",
                        "Ireland",
                        "Israel",
                        "Italy",
                        "Jamaica",
                        "Japan",
                        "Jordan",
                        "Kazakhstan",
                        "Kenya",
                        "Kiribati",
                        "North Korea ",
                        "South Korea ",
                        "Kosovo",
                        "Kuwait",
                        "Kyrgyzstan",
                        "Laos",
                        "Latvia",
                        "Lebanon",
                        "Lesotho",
                        "Liberia",
                        "Libya",
                        "Liechtenstein",
                        "Lithuania",
                        "Luxembourg",
                        "Macau",
                        "Macedonia",
                        "Madagascar",
                        "Malawi",
                        "Malaysia",
                        "Maldives",
                        "Mali",
                        "Malta",
                        "Marshall Islands",
                        "Mauritania",
                        "Mauritius",
                        "Mexico",
                        "Micronesia",
                        "Moldova",
                        "Monaco",
                        "Mongolia",
                        "Montenegro",
                        "Morocco",
                        "Mozambique",
                        "Namibia",
                        "Nauru",
                        "Nepal",
                        "Netherlands",
                        "New Zealand",
                        "Nicaragua",
                        "Niger",
                        "Nigeria",
                        "North Korea",
                        "Norway",
                        "Oman",
                        "Pakistan",
                        "Palau",
                        "Palestinian Territories",
                        "Panama",
                        "Papua New Guinea",
                        "Paraguay",
                        "Peru",
                        "Philippines",
                        "Poland",
                        "Portugal",
                        "Qatar",
                        "Romania",
                        "Russia",
                        "Rwanda",
                        "Saint Kitts and Nevis",
                        "Saint Lucia",
                        "Saint Vincent and the Grenadines",
                        "Samoa ",
                        "San Marino",
                        "Sao Tome and Principe",
                        "Saudi Arabia",
                        "Senegal",
                        "Serbia",
                        "Seychelles",
                        "Sierra Leone",
                        "Singapore",
                        "Sint Maarten",
                        "Slovakia",
                        "Slovenia",
                        "Solomon Islands",
                        "Somalia",
                        "South Africa",
                        "South Korea",
                        "South Sudan",
                        "Spain ",
                        "Sri Lanka",
                        "Sudan",
                        "Suriname",
                        "Swaziland ",
                        "Sweden",
                        "Switzerland",
                        "Syria",
                        "Taiwan",
                        "Tajikistan",
                        "Tanzania",
                        "Thailand ",
                        "Timor-Leste",
                        "Togo",
                        "Tonga",
                        "Trinidad and Tobago",
                        "Tunisia",
                        "Turkey",
                        "Turkmenistan",
                        "Tuvalu",
                        "Uganda",
                        "Ukraine",
                        "United Arab Emirates",
                        "United Kingdom",
                        "Uruguay",
                        "Uzbekistan",
                        "Vanuatu",
                        "Venezuela",
                        "Vietnam",
                        "Yemen",
                        "Zambia",
                        "Zimbabwe");
        return " in " . Helper::random($data);
    }

    static public function conectors()
    {
        $data = array(  "and", "while", "untill" );
        return " " . Helper::random($data) . " ";
    }

    static public function getTitle()
    {
        $title = (Helper::random(2,1) == 1)? self::artists(): self::superHeores();
        $title .= " ";

        $tmpVal = self::actions();
        if($tmpVal[1] === 1)
        {
            $action = self::adverbs() . " " . $tmpVal[0] . " ";
            $action .= (Helper::random(2,1) == 1)? self::artists(): self::superHeores();
        } else {
            $action =  $tmpVal[0] . " " . self::adverbs();
        }

        $title .= $action;

        if(Helper::random(2,1) == 1)
        {
            $title .= self::countries();
        }

        return $title;
    }

    static public function getParagraph()
    {
        $paragraph = "";
        $count= Helper::random(8,3);
        for ($i=0; $i <=  $count; $i++)
        {
            $paragraph .= trim(self::getTitle());
            if($i < $count -1){   $paragraph .=  self::conectors();}
        }
        return $paragraph . ".";
    }

    static public function getBody()
    {
        $count= Helper::random(10,3);
        $body = "";
        for ($i=0; $i <=  $count; $i++)
        {
            $body .= self::getParagraph() . "\n\n";
        }
        return $body;
    }

}


echo("\n\e[1;32m".Data::getTitle()."\n\n\e[0m\n");
echo("\e[1;35m".Data::getBody()."\e[0m\n");
